### PR TITLE
Initialized Redux 

### LINKED ISSUE #13: Setup `redux`
- [x] Investigate use case for `redux` within application
- [x] adding `react-redux` to `devDependencies`
- [x] setting up actions
- [x] setting up reducers
- [x] setting up store

> Investigation & Implementation

### PR DESCRIPTION
**Pull request by tonyguo665**
boilerplate code with comments indicating the purpose of each section

fixes #13 
@jarrodchung-dev 
@gbzaid2 

Review needed!

### CODE REVIEW

**Comment by jrd404** [comment]
@tonyguo665 Holding review per your request.

Please update when ready.

**Comment by tonyguo665** [comment]
Edits have been made and ready for Review/Merge
@jarrodchung-dev 
@gbzaid2

**Comment by jarrodchung-dev** [comment]
#13

**Comment by jarrodchung-dev** [comment]
#13

**Pull request merged**
